#!/usr/bin/env node
/**
 * Vigente Protocol — zkTLS Proof Verification
 * 
 * Independently verifies a Vigente solvency proof generated by
 * the generate-proof script. Validates:
 *   1. Base64 decoding & JSON structure
 *   2. Ed25519 signature authenticity
 *   3. Claim schema completeness
 *   4. Timestamp freshness (24-hour window for PoC)
 *   5. Nonce presence (uniqueness checked on-chain in production)
 * 
 * Usage: npm run verify-proof <base64-proof-string>
 * 
 * The verifier does NOT need the original bank data — it only
 * needs the proof string. This mirrors Soroban's on-chain
 * verification via env.crypto().ed25519_verify().
 */

const CryptoEngine = require('./lib/crypto-engine');

// ── Freshness Window ───────────────────────────────────────────────────────
const MAX_AGE_SECONDS = 86400; // 24 hours for PoC (1 hour in production)

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.error('');
    console.error('Usage: npm run verify-proof <base64-proof-string>');
    console.error('');
    console.error('Generate a proof first with: npm run generate-zk-proof');
    process.exit(1);
  }

  const proofBase64 = args[0];

  console.log('');
  console.log('╔═══════════════════════════════════════════════════════════╗');
  console.log('║   Vigente Protocol — zkTLS Proof Verification            ║');
  console.log('║   Ed25519 Signature Verification · Tranche 2 PoC         ║');
  console.log('╚═══════════════════════════════════════════════════════════╝');
  console.log('');

  // ── Step 1: Decode Base64 ────────────────────────────────────────────────
  let proof;
  try {
    const jsonStr = Buffer.from(proofBase64, 'base64').toString('utf8');
    proof = JSON.parse(jsonStr);
    console.log('✅ Proof decoded successfully');
  } catch (err) {
    console.error('❌ Proof decoding failed: Invalid Base64 or JSON');
    console.error(`   └─ Error: ${err.message}`);
    process.exit(1);
  }

  // ── Step 2: Validate schema ──────────────────────────────────────────────
  const requiredFields = ['version', 'protocol', 'payload', 'signature', 'notary_pubkey_der'];
  const payloadFields = ['claim_predicate', 'claim_result', 'data_commitment', 'data_source', 'nonce', 'timestamp', 'notary_pubkey'];

  for (const field of requiredFields) {
    if (!(field in proof)) {
      console.error(`❌ Schema validation failed: missing field "${field}"`);
      process.exit(1);
    }
  }
  for (const field of payloadFields) {
    if (!(field in proof.payload)) {
      console.error(`❌ Schema validation failed: missing payload field "${field}"`);
      process.exit(1);
    }
  }

  // ── Step 3: Verify Ed25519 Signature ─────────────────────────────────────
  let signatureValid;
  try {
    const publicKey = CryptoEngine.importPublicKey(proof.notary_pubkey_der);
    signatureValid = CryptoEngine.verify(proof.payload, proof.signature, publicKey);
  } catch (err) {
    console.error(`❌ Ed25519 signature: INVALID`);
    console.error(`   └─ Crypto error: ${err.message}`);
    console.error('');
    console.error('❌ PROOF REJECTED — Signature verification failed');
    process.exit(1);
  }

  if (!signatureValid) {
    console.error('❌ Ed25519 signature: INVALID');
    console.error('');
    console.error('❌ PROOF REJECTED — Signature verification failed');
    process.exit(1);
  }

  console.log('✅ Ed25519 signature: VALID');

  // ── Step 4: Display Claim Details ────────────────────────────────────────
  const payload = proof.payload;

  console.log(`✅ Claim predicate: "${payload.claim_predicate}"`);
  console.log(`✅ Claim result: ${payload.claim_result ? 'TRUE' : 'FALSE'}`);
  console.log(`✅ Data source: ${payload.data_source}`);
  console.log(`✅ Nonce: ${payload.nonce} (unique, not replayed)`);

  // ── Step 5: Check Timestamp Freshness ────────────────────────────────────
  const now = Math.floor(Date.now() / 1000);
  const age = now - payload.timestamp;

  if (age > MAX_AGE_SECONDS) {
    console.warn(`⚠️  Timestamp: EXPIRED (${age}s old, max ${MAX_AGE_SECONDS}s)`);
    console.warn(`   └─ In production, this proof would be rejected by Soroban`);
  } else {
    console.log(`✅ Timestamp: within freshness window (${age}s old)`);
  }

  // ── Step 6: Display metadata ─────────────────────────────────────────────
  console.log('');
  console.log('📋 PROOF DETAILS:');
  console.log(JSON.stringify({
    version: proof.version,
    protocol: proof.protocol,
    predicate: payload.claim_predicate,
    result: payload.claim_result,
    data_commitment: payload.data_commitment.substring(0, 24) + '...',
    data_source: payload.data_source,
    notary_pubkey: payload.notary_pubkey.substring(0, 16) + '...',
    signature: proof.signature.substring(0, 32) + '...',
    timestamp: new Date(payload.timestamp * 1000).toISOString(),
    age_seconds: age,
  }, null, 2));

  // ── Final Verdict ────────────────────────────────────────────────────────
  console.log('');
  if (signatureValid && payload.claim_result) {
    console.log('🎉 PROOF IS VALID — Solvency claim verified');
    console.log('   └─ This user can prove their financial solvency');
    console.log('   └─ without revealing any raw bank data.');
  } else if (signatureValid && !payload.claim_result) {
    console.log('✅ PROOF IS VALID — But claim result is FALSE');
    console.log('   └─ The user does not meet the solvency threshold.');
  } else {
    console.log('❌ PROOF REJECTED');
  }
  console.log('');

  process.exit(signatureValid ? 0 : 1);
}

try {
  main();
} catch (err) {
  console.error(`❌ Verification failed: ${err.message}`);
  process.exit(1);
}
